### ISSUE TITLE
Error messages should disappear when node is restarted.

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#139]
![image](https://user-images.githubusercontent.com/47108/55581159-271c1a80-56ea-11e9-8768-cd85ecb080fe.png)

**Comment by ryanio** [comment]
Hmmm now that the error message is in a closable snackbar, I think this is okay, because the error is user dismissible.

I would prefer the user to read, acknowledge, and close it, rather than it to disappear on restart. That said, for it to dissapear on restart, it would be as easy as dispatching the clearError action on geth.on('started')
