### ISSUE TITLE
Parity process does not exit when closing app

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/grid#267]
![image](https://user-images.githubusercontent.com/47108/59396502-14136f80-8d57-11e9-98c4-83af460b136c.png)

goes with failing test as a bonus: https://github.com/ethereum/grid/commit/aa56eff4080f07da453d0bda12f647e38a14fb01

**Comment by marcgarreau** [comment]
Poking around here... the proc does eventually successfully get killed (and reaches `STOPPED` state) if left alone for long enough to hit Parity's timeout:
<img width="1212" alt="Screen Shot 2019-08-29 at 10 22 45 AM" src="https://user-images.githubusercontent.com/3621728/63959496-88ea7180-ca49-11e9-89cf-508f7376a54d.png">
So, that's encouraging, but waiting 5 mins between restarts is a pretty good buzzkill for prototyping standards. `kill('SIGQUIT')` (rather than `'SIGINT`) does nuke the Parity proc and looks relatively clean from a UI perspective, but at the expense of not shutting down other processes (e.g. Geth) cleanly. Continuing down the rabbit hole...
