### ISSUE TITLE
Trigger CI release process for new mist(-ui)-react versions 

### ISSUE THREAD

**Issue by PhilippLgh** [ethereum/grid#3]
We want the CI to build a new release draft whenever a new mist(-ui)-react version is released to:
https://github.com/ethereum/mist-ui-react/releases

After the build is tested and changed from draft to release this should NOT trigger electron-builder's auto-updater because electron-app-updater will take care of updating installed versions.

**Comment by evertonfraga** [comment]
1st try: using **Create Release** webhook pointing to the circleCI new build URL form mist-shell
❌ It failed due to the default POST parameters Github sends (and it's not configurable).

2nd try: create a CircleCI job that will only run when a tag is created, and calls mist-shell CircleCI endpoint to trigger a build from master branch.

**Comment by evertonfraga** [comment]
PR available here: https://github.com/ethereum/mist-ui-react/pull/3
