### ISSUE TITLE
Why isn't Geth 1.9.9 showing up on the version list yet?

### ISSUE THREAD

**Issue by brantlymillegan** [ethereum/grid#527]
Am I missing something? Thanks for the help, don't want to miss upgrading with the upcoming fork.

<img width="1157" alt="Screen Shot 2019-12-23 at 3 09 25 PM" src="https://user-images.githubusercontent.com/30162762/71384458-44ee2000-2596-11ea-8f7a-26d751a975a2.png">

**Comment by ryanio** [comment]
Thanks @brantlymillegan for the report.

I can confirm 1.9.9 is currently not showing up for me either in Grid UI.

We will investigate further and let you know.

**Comment by PhilippLgh** [comment]
@brantlymillegan Grid caches the version list but has known issues with invalidating the cache. I assume that Grid was not closed and a new version was releases after the list was cached. Restarting Grid will probably fix the issue if this is the case.

**Comment by brantlymillegan** [comment]
So I closed Grid and reopened it. I also did a "Forced Reload" (not sure what that means). Still not seeing Get 1.9.9

**Comment by ryanio** [comment]
Hey @brantlymillegan thanks for your continued patience here.

After some more investigative work I did find a bug that the 1.9.9 release was being omitted from the version list due to a rare and interesting parsing error.

We hope to release a fix soon so you can be on track for Muir Glacier 😎

I believe as soon as we publish the release, the next time you open Grid you will get a notification to auto update.

**Comment by brantlymillegan** [comment]
Great, thanks! Looking forward to upgrading

**Comment by amateur-dev** [comment]
Yup; waiting for this eagerly!  Thank you.

**Comment by brantlymillegan** [comment]
Just to update: Geth V1.9.10 is showing up on the list (but not Geth V1.9.9), and it's working!
